<?php

/**
 * @file
 * Render a Streaming Audio player as a Drupal Block.
 */

/**
 * Implementation hook_perm().
 */
function audio_streaming_player_perm() {
  return array('administer audiostreamingplayer', 'access audiostreamingplayer configuration');
}

/*
 * Implementation of hook_permission()
 */
function audio_streaming_player_permission() {
  return array(
    'administer audiostreamingplayer' => array(
      'title' => t('Audio Streaming Player permission'),
      'description' => t('Allows users to perform a task in Audio Streaming Player'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function audio_streaming_player_menu() {
  $items = array();
  //Link of menu:
  $items['admin/config/media/audioStreamingPlayer'] = array(
    'title' => 'Audio Streaming Player',
    'description' => 'Administer Audio Streaming Player Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('audio_streaming_player_form'),
    'access arguments' => array('administer audiostreamingplayer'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implement the hook_form
 * Create a form for configuring the module
 * @return type
 */
function audio_streaming_player_form() {
  //Stream Url
  $form['stream_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter the Stream URL'),
    '#default_value' => variable_get('stream_url'),
    '#size' => 75,
    '#maxlength' => 180,
    '#required' => TRUE
  );


  //Themes
  $options = array(
    0 => t('Black Player' . '<img align="left" width="133px" heigth="180px" src=/' . drupal_get_path('module', 'audio_streaming_player') . '/themes/audio_streaming_player_black/thumbnail.png/></br></br></br></br>'),
    1 => t('Circular Player' . '<img align="left" src=/' . drupal_get_path('module', 'audio_streaming_player') . '/themes/audio_streaming_player_circular/thumbnail.png/></br></br></br></br>'),
    2 => t('Only Text' . '<img align="left" src=/' . drupal_get_path('module', 'audio_streaming_player') . '/themes/audio_streaming_player_text/thumbnail.png/></br></br></br></br>')
  );
  $form['theme'] = array(
    '#type' => 'radios',
    '#title' => t('Select the theme for the player'),
    '#default_value' => variable_get('theme'),
    '#options' => $options
  );

  //Auto-Play Option
  $form['auto_play'] = array(
    '#type' => 'checkbox',
    '#default_value' => variable_get('auto_play'),
    '#title' => t('Auto Play'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save'
  );

  return ($form);
}

/**
 * Form submission for user data.
 * @param form an array that contains user data
 * @param form_state an array that contains user data
 */
function audio_streaming_player_form_submit($form, &$form_state) {
  //get data
  $stream_url = $form_state['values']['stream_url'];
  $theme = $form_state['values']['theme'];
  $auto_play = $form_state['values']['auto_play'];

  //Set variables
  $stream_url_set = variable_set('stream_url', ($form_state['values']['stream_url']));
  $theme_set = variable_set('theme', ($form_state['values']['theme']));
  $auto_play_set = variable_set('auto_play', ($form_state['values']['auto_play']));


  //Confirmation message
  drupal_set_message(t('The configuration options have been saved'));
  $form_state['redirect'] = 'admin/config/media/audioStreamingPlayer';
}

/**
 * Implementes hook_libraries_info
 * @return array with information from the libraries it needs the module
 */
function audio_streaming_player_libraries_info() {
  $libraries = array();
  $libraries['JPayer'] = array(
    'name' => 'JPlayer',
    'vendor url' => 'http://www.jplayer.org/',
    'download url' => 'http://www.jplayer.org/latest/jQuery.jPlayer.2.6.0.source.zip',
    'version arguments' => array(
      'file' => 'jquery.jplayer.min.js',
      // jQuery FlexSlider v2.1
      'pattern' => '/jQuery JPlayer v(\d+\.+\d+)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array(
        'jquery.jplayer.min.js',
      ),
    ),
  );


  return $libraries;
}

/**
 * Implementation of hook_block_info()
 * @return  the information of the block
 */
function audio_streaming_player_block_info() {
  $blocks['streamingplayer'] = array(
    'info' => t('Audio Streaming player Block'),
  );
  return $blocks;
}

/**
 *  Implementation of hook_block_view()
 * 
 */
function audio_streaming_player_block_view($delta = '') {
  //Identify the selected theme
  switch (variable_get('theme')) {
    case 0:
      $theme = 'audio_streaming_player_black';
      break;
    case 1:
      $theme = 'audio_streaming_player_circular';
      break;
    case 2:
      $theme = 'audio_streaming_player_text';
      break;
  }

  $block = array();

  switch ($delta) {
    case 'streamingplayer':
      $block['content'] = array(
        '#markup' => theme("$theme", array('theme' => "")),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'audio_streaming_player') . '/themes/' . "$theme" . '/css/' . "$theme" . '.css',
          ),
          //Libraries 
          'js' => array(
            libraries_get_path('JPlayer') . '/jquery.jplayer.min.js',
            drupal_get_path('module', 'audio_streaming_player') . '/themes/' . "$theme" . '/js/' . "$theme" . '.js',
            libraries_get_path('JPlayer') . '/add-on/jquery.jplayer.inspector.js',
            drupal_add_js(array('audiostreamingplayer' => array('swf' => '/' . libraries_get_path('JPlayer') . '/', 'stream_url' => variable_get('stream_url'), 'auto_play' => variable_get('auto_play'))), 'setting'),
          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme()
 */
function audio_streaming_player_theme() {
  return array(
    'audio_streaming_player_circular' => array(
      'variables' => array('account' => NULL),
      'template' => 'themes/audio_streaming_player',
    ),
    'audio_streaming_player_black' => array(
      'variables' => array('account' => NULL),
      'template' => 'themes/audio_streaming_player',
    ),
    'audio_streaming_player_text' => array(
      'variables' => array('account' => NULL),
      'template' => 'themes/audio_streaming_player_text/audio_streaming_player_text',
    )
  );
}
