<?php

/**
 * @file
 * Render a Streaming Audio player as a Drupal Block.
 */

/**
 * Implements hook_perm().
 */
function audio_streaming_player_perm() {
  return array('administer audiostreamingplayer', 'access audiostreamingplayer configuration');
}

/**
 * Implements hook_permission().
 */
function audio_streaming_player_permission() {
  return array(
    'administer audiostreamingplayer' => array(
      'title' => t('Audio Streaming Player permission'),
      'description' => t('Allows users to perform a task in Audio Streaming Player'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function audio_streaming_player_menu() {
  $items = array();
  // Link of menu:
  $items['admin/config/media/audioStreamingPlayer'] = array(
    'title' => 'Audio Streaming Player',
    'description' => 'Administer Audio Streaming Player Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('audio_streaming_player_form'),
    'access arguments' => array('administer audiostreamingplayer'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_form().
 */
function audio_streaming_player_form() {
  $form['audio_streaming_player_stream_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter the Stream URL'),
    '#default_value' => variable_get('audio_streaming_player_stream_url'),
    '#size' => 75,
    '#maxlength' => 180,
    '#required' => TRUE,
  );
  $option0 = 'Black Player' . '<img align="left" width="133px" heigth="180px" src=/' . drupal_get_path('module', 'audio_streaming_player') . '/themes/audio_streaming_player_black/thumbnail.png/></br></br></br></br>';
  $option1 = 'Circular Player' . '<img align="left" src=/' . drupal_get_path('module', 'audio_streaming_player') . '/themes/audio_streaming_player_circular/thumbnail.png/></br></br></br></br>';
  $option2 = 'Only Text' . '<img align="left" src=/' . drupal_get_path('module', 'audio_streaming_player') . '/themes/audio_streaming_player_text/thumbnail.png/></br></br></br></br>';
// Skins.
  $options = array(
    0 => t($option0),
    1 => t($option1),
    2 => t($option2),
  );
  $form['audio_streaming_player_theme'] = array(
    '#type' => 'radios',
    '#title' => t('Select the theme for the player'),
    '#default_value' => variable_get('audio_streaming_player_theme'),
    '#options' => $options,
  );
  // Auto-Play Option.
  $form['audio_streaming_player_auto_play'] = array(
    '#type' => 'checkbox',
    '#default_value' => variable_get('audio_streaming_player_auto_play'),
    '#title' => t('Auto Play'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save',
  );

  return ($form);
}

/**
 * Implements hook_form_submit().
 */
function audio_streaming_player_form_submit($form, &$form_state) {
  // Set variables.
  variable_set('audio_streaming_player_stream_url', ($form_state['values']['audio_streaming_player_stream_url']));
  variable_set('audio_streaming_player_theme', ($form_state['values']['audio_streaming_player_theme']));
  variable_set('audio_streaming_player_auto_play', ($form_state['values']['audio_streaming_player_auto_play']));
  // Confirmation message.
  drupal_set_message(t('The configuration options have been saved'));
  $form_state['redirect'] = 'admin/config/media/audioStreamingPlayer';
}

/**
 * Implements hook_libraries_info().
 */
function audio_streaming_player_libraries_info() {
  $libraries = array();
  $libraries['JPayer'] = array(
    'name' => 'JPlayer',
    'vendor url' => 'http://www.jplayer.org/',
    'download url' => 'http://www.jplayer.org/latest/jQuery.jPlayer.2.6.0.source.zip',
    'version arguments' => array(
      'file' => 'jquery.jplayer.min.js',
      'pattern' => '/jQuery JPlayer v(\d+\.+\d+)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array(
        'jquery.jplayer.min.js',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_block_info().
 */
function audio_streaming_player_block_info() {
  $blocks['streamingplayer'] = array(
    'info' => t('Audio Streaming player Block'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function audio_streaming_player_block_view($delta = '') {
  // Identify the selected theme.
  switch (variable_get('audio_streaming_player_theme')) {
    case 0:
      $audio_streaming_player_theme = 'audio_streaming_player_black';
      break;

    case 1:
      $audio_streaming_player_theme = 'audio_streaming_player_circular';
      break;

    case 2:
      $audio_streaming_player_theme = 'audio_streaming_player_text';
      break;
  }

  $block = array();

  switch ($delta) {
    case 'streamingplayer':
      $block['content'] = array(
        '#markup' => theme("$audio_streaming_player_theme", array('theme' => "")),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'audio_streaming_player') . '/themes/' . "$audio_streaming_player_theme" . '/css/' . "$audio_streaming_player_theme" . '.css',
          ),
          // Libraries. 
          'js' => array(
            libraries_get_path('JPlayer') . '/jquery.jplayer.min.js',
            drupal_get_path('module', 'audio_streaming_player') . '/themes/' . "$audio_streaming_player_theme" . '/js/' . "$audio_streaming_player_theme" . '.js',
            libraries_get_path('JPlayer') . '/add-on/jquery.jplayer.inspector.js',
            drupal_add_js(array('audiostreamingplayer' => array('swf' => '/' . libraries_get_path('JPlayer') . '/', 'audio_streaming_player_stream_url' => variable_get('audio_streaming_player_stream_url'), 'audio_streaming_player_auto_play' => variable_get('audio_streaming_player_auto_play'))), 'setting'),
          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function audio_streaming_player_theme() {
  return array(
    'audio_streaming_player_circular' => array(
      'variables' => array('account' => NULL),
      'template' => 'themes/audio_streaming_player',
    ),
    'audio_streaming_player_black' => array(
      'variables' => array('account' => NULL),
      'template' => 'themes/audio_streaming_player',
    ),
    'audio_streaming_player_text' => array(
      'variables' => array('account' => NULL),
      'template' => 'themes/audio_streaming_player_text/audio_streaming_player_text',
    ),
  );
}
